image:
    file: .gitpod.Dockerfile
ports:
    - port: 6080
tasks:
    - init: >
        sudo apt update &&
        sudo apt install -y unar curl &&
        curl -fsSL https://crystal-lang.org/install.sh | sudo bash
